server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_journey?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: zelongwen
    password: Wenzl@2018
  main:
    allow-circular-references: true


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      wrap-root-value: false # env variables

SPARKPOST_API_KEY: 0cce3a0b7ea7d58f4ca86f19425774b37d79cf6c
SP_BASE_URI: https://api.sparkpost.com
TESTING_DOMAIN: paradx.dev

corn:
  expressions:
    everySecond: "*/1 * * * * ?"
    everyTenSecond: "*/10 * * * * ?"
#    never: "0 0 0 30 2 ?"

redis-key:
  in-queue-key: "InQueue"
  out-queue-key: "OutQueue"
  task-queue-key: "CoretaskQueue"
