server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/email_automation
    username: root
    password: shanghai123$

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
