server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_journey?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: shanghai123$

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      wrap-root-value: false # env variables

SPARKPOST_API_KEY: 358294aeb167a63aa0ade3a287ef013559e3d964
SP_BASE_URI: https://api.sparkpost.com
TESTING_DOMAIN: sub.paradx.net
#  jackson:
#    serialization:
#      wrap-root-value: true # env variables

#SPARKPOST_API_KEY: 358294aeb167a63aa0ade3a287ef013559e3d964
#SP_BASE_URI: https://api.sparkpost.com
#TESTING_DOMAIN: sub.paradx.net
